services:
  db:
    image: postgres
    volumes:
      - ./../DataBaseCloudDrive/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5431:5432
  web:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

